-- ============================================================
-- Local development/test schema — mirrors production structure
-- ============================================================

-- Projects
create table if not exists public.projects_new (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'Web Development',
  description text not null,
  link text,
  image_url text,
  color text default '#a855f7',
  is_featured boolean default false,
  sort_order integer default 0,
  created_at timestamptz default now()
);

-- Site settings (single row)
create table if not exists public.site_settings (
  id smallint primary key default 1 check (id = 1),
  email text default 'info@innovelous.com',
  phone text default '+92 333 2186309',
  office_location text default 'Pakistan',
  office_address text default 'DHA Phase 2 (Extension), Karachi',
  facebook_url text default 'https://www.facebook.com/innoveloustech',
  github_url text default 'https://github.com/innoveloustech',
  instagram_url text default 'https://www.instagram.com/innoveloustech',
  whatsapp_url text default 'https://wa.me/923349251936',
  logo_url text default '/logo.png',
  favicon_url text default '/favicon.ico',
  og_image_url text default '/og-image.jpg',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  show_featured boolean default true
);

-- Testimonials
create table if not exists public.testimonials (
  id smallint primary key,
  text text not null,
  author text not null,
  role text default '',
  is_dark boolean default true,
  sort_order smallint default 0
);

-- FAQs
create table if not exists public.faqs (
  id smallint primary key,
  question text not null,
  answer text not null,
  sort_order smallint default 0
);

-- ============================================================
-- Row Level Security — same policies as production
-- ============================================================
alter table public.projects_new enable row level security;
alter table public.site_settings enable row level security;
alter table public.testimonials enable row level security;
alter table public.faqs enable row level security;

-- projects_new
create policy "Public can view projects"
  on public.projects_new for select to public using (true);
create policy "Authenticated users can insert projects"
  on public.projects_new for insert to public with check (auth.role() = 'authenticated');
create policy "Authenticated users can update projects"
  on public.projects_new for update to public using (auth.role() = 'authenticated');
create policy "Authenticated users can delete projects"
  on public.projects_new for delete to public using (auth.role() = 'authenticated');

-- site_settings
create policy "Anyone can view site settings"
  on public.site_settings for select to public using (true);
create policy "Authenticated users can insert site settings"
  on public.site_settings for insert to public with check (auth.role() = 'authenticated');
create policy "Authenticated users can update site settings"
  on public.site_settings for update to public using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- testimonials
create policy "Anyone can view testimonials"
  on public.testimonials for select to public using (true);
create policy "Authenticated users can insert testimonials"
  on public.testimonials for insert to public with check (auth.role() = 'authenticated');
create policy "Authenticated users can update testimonials"
  on public.testimonials for update to public using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- faqs
create policy "Anyone can view faqs"
  on public.faqs for select to public using (true);
create policy "Authenticated users can insert faqs"
  on public.faqs for insert to public with check (auth.role() = 'authenticated');
create policy "Authenticated users can update faqs"
  on public.faqs for update to public using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- ============================================================
-- Role privileges — same as Supabase production defaults
-- (RLS policies still gate every row access)
-- ============================================================
grant usage on schema public to postgres, anon, authenticated, service_role;
grant all on all tables in schema public to postgres, anon, authenticated, service_role;
grant all on all sequences in schema public to postgres, anon, authenticated, service_role;
grant all on all routines in schema public to postgres, anon, authenticated, service_role;

-- ============================================================
-- Storage buckets (same ids as production)
-- ============================================================
insert into storage.buckets (id, name, public)
values
  ('projects_new-images', 'projects_new-images', true),
  ('site-assets', 'site-assets', true)
on conflict (id) do nothing;

-- ============================================================
-- Seed data
-- ============================================================
insert into public.site_settings (id)
values (1)
on conflict (id) do nothing;

insert into public.testimonials (id, text, author, role, is_dark, sort_order) values
  (1, 'Outstanding team! They delivered our platform ahead of schedule with flawless quality.', 'Ahmed Raza', 'CEO, TechNova', true, 0),
  (2, 'Innovelous transformed our outdated site into a modern experience. Highly recommended.', 'Sara Khan', 'Founder, BrightMinds', false, 1),
  (3, 'Professional, responsive and creative. A pleasure to work with from start to finish.', 'Bilal Ahmed', 'Product Lead, CloudDesk', true, 2),
  (4, 'Their attention to detail and innovative approach exceeded all our expectations.', 'Fatima Noor', 'Marketing Head, UrbanCart', false, 3)
on conflict (id) do nothing;

insert into public.faqs (id, question, answer, sort_order) values
  (1, 'What services do you offer?', 'We specialize in web development, mobile apps, UI/UX design and digital transformation.', 0),
  (2, 'How long does a typical project take?', 'Most projects take 4-8 weeks depending on scope and complexity.', 1),
  (3, 'Do you provide post-launch support?', 'Yes, we offer maintenance plans and dedicated support after launch.', 2),
  (4, 'How do we get started?', 'Contact us through the form on our website and we will schedule a free consultation.', 3)
on conflict (id) do nothing;

-- ============================================================
-- Local test user (admin@innovelous.com / test-password-123)
-- Used by integration tests running against the local stack only
-- ============================================================
insert into auth.users (
  instance_id, id, aud, role, email,
  encrypted_password, email_confirmed_at, invited_at,
  confirmation_token, confirmation_sent_at,
  recovery_token, recovery_sent_at,
  email_change_token_new, email_change, email_change_sent_at,
  email_change_token_current, email_change_confirm_status,
  last_sign_in_at, raw_app_meta_data, raw_user_meta_data,
  is_super_admin, created_at, updated_at,
  phone, phone_confirmed_at, phone_change, phone_change_token, phone_change_sent_at,
  reauthentication_token, reauthentication_sent_at,
  is_sso_user, deleted_at, is_anonymous
) values (
  '00000000-0000-0000-0000-000000000000',
  '11111111-1111-1111-1111-111111111111',
  'authenticated', 'authenticated', 'admin@innovelous.com',
  crypt('test-password-123', gen_salt('bf', 10)),
  now(), null,
  '', null,
  '', null,
  '', '', null,
  '', 0,
  now(), '{"provider":"email","providers":["email"]}', '{}',
  false, now(), now(),
  null, null, '', '', null,
  '', null,
  false, null, false
)
on conflict (id) do nothing;

insert into auth.identities (
  id, user_id, provider_id, identity_data, provider,
  last_sign_in_at, created_at, updated_at
) values (
  '11111111-1111-1111-1111-111111111111',
  '11111111-1111-1111-1111-111111111111',
  '11111111-1111-1111-1111-111111111111',
  jsonb_build_object('sub', '11111111-1111-1111-1111-111111111111', 'email', 'admin@innovelous.com', 'email_verified', true, 'phone_verified', false),
  'email', now(), now(), now()
)
on conflict (id) do nothing;